image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    addCheck: false
    addComment: false
    addBadge: true

ports:
  - name: web
    port: 8000
    visibility: public
    onOpen: open-preview
      
tasks:
  - name: Fresh
    command: deno task start --watch
      
