image:
  file: .gitpod.Docker

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    addCheck: false
    addComment: false
    addBadge: true

ports:
  - name: web
    port: 1993
    visibility: public
    onOpen: open-preview

jetbrains:
  webstorm:
    prebuilds:
      version: stable
    plugins:
      - izhangzhihao.rainbow.brackets
      
tasks:
  - name: Fresh
    init: deno run -A -r https://fresh.deno.dev .
    command: deno task start --watch
      
