image:
  file: Dockerfile

github:
  prebuilds:
    main: true
    branches: true
    pullRequests: true
    addCheck: false
    addComment: false
    addBadge: true

tasks:
  - command: |
    deno --version
    deno run --allow-net ./main.ts
ports:
  - port: 8000
jetbrains:
  - jetbrains.webstorm
